"""Part of Module 9 — Audio Production (SFX/ambience).

Generates ambient soundscapes and one-shot sound effects using Stable Audio 3
Small SFX. The existing sound cue prompt strings (already LLM-generated by
Module 1) are passed directly to the AI model, enriched with the scene's
emotional_tone for coloring.

Replaces the old procedural numpy/scipy ambience and one-shot synthesizers.
"""

from __future__ import annotations

from pydub import AudioSegment

from .mood import classify_mood
from .stable_audio_client import generate_sfx

# ---------------------------------------------------------------------------
# Emotion → ambience coloring suffix
# ---------------------------------------------------------------------------

_MOOD_AMBIENCE_SUFFIX: dict[str, str] = {
    "joy":        "bright and warm atmosphere, pleasant",
    "warm":       "cozy and intimate atmosphere",
    "calm":       "peaceful and serene, very quiet",
    "sad":        "lonely and desolate, muted and dark",
    "mysterious": "eerie and unsettling, strange tonal quality",
    "fear":       "tense and ominous, low rumble underneath, dread",
    "anger":      "harsh and aggressive, heavy and oppressive",
    "surprise":   "sharp and sudden, heightened energy",
    "neutral":    "neutral atmospheric texture",
}


def _enrich_ambience_prompt(prompt: str, emotional_tone: str) -> str:
    """Combine the scene's literal sound-cue prompt with an emotional coloring suffix."""
    mood = classify_mood(emotional_tone)
    suffix = _MOOD_AMBIENCE_SUFFIX.get(mood, _MOOD_AMBIENCE_SUFFIX["neutral"])
    return f"{prompt}, {suffix}, ambient sound design, field recording quality"


def _enrich_oneshot_prompt(prompt: str) -> str:
    """Enrich one-shot SFX prompts for Stable Audio SFX model."""
    return f"{prompt}, sound effect, high quality audio, isolated"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_ambience(
    prompt: str, duration_ms: int, emotional_tone: str = "", seed: int | None = None
) -> AudioSegment:
    """Generate an ambient soundscape using Stable Audio 3 Small SFX.

    Args:
        prompt: LLM-generated description of the ambience (e.g. "dark forest at night").
        duration_ms: Target duration in milliseconds.
        emotional_tone: Scene's emotional tone for mood coloring.
        seed: Unused (kept for API compatibility).

    Returns:
        AudioSegment with AI-generated ambience.

    Raises:
        RuntimeError: If Stable Audio generation fails.
    """
    if duration_ms <= 0:
        return AudioSegment.silent(duration=0)

    enriched_prompt = _enrich_ambience_prompt(prompt, emotional_tone)
    return generate_sfx(enriched_prompt, duration_ms)


def generate_one_shot(prompt: str, seed: int | None = None) -> AudioSegment:
    """Generate a one-shot sound effect using Stable Audio 3 Small SFX.

    Args:
        prompt: LLM-generated description of the sound (e.g. "door creaking open").
        seed: Unused (kept for API compatibility).

    Returns:
        AudioSegment with AI-generated one-shot SFX.

    Raises:
        RuntimeError: If Stable Audio generation fails.
    """
    enriched_prompt = _enrich_oneshot_prompt(prompt)
    # duration_ms=0 → model picks natural length, trimmed to minimum 1s in client
    return generate_sfx(enriched_prompt, duration_ms=0)
